run:
  build-tags:
    - mage
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - lll
  disable:
    - ireturn 
    - depguard
    - gochecknoglobals # Immutable globals are fine.
    - exhaustruct # Often the case for protobuf generated code or gorm structs.
    - protogetter # We do want to use pointers for memory optimization.
  presets:
    - bugs
    - comment
    - complexity
    - error
    - format
    - import
    - metalinter
    - module
    - performance
    - sql
    - style
    - test
    - unused

linters-settings:
  gci:
    custom-order: true

    sections:
      - standard # Standard section: captures all standard packages.
      - default # Default section: contains all imports that could not be matched to another section type.
      - alias # Alias section: contains all alias imports. This section is not present unless explicitly enabled.
      - prefix(github.com/mlflow/mlflow-go) # Custom section: groups all imports with the specified Prefix.
      - blank # Blank section: contains all blank imports. This section is not present unless explicitly enabled.
      - dot # Dot section: contains all dot imports. This section is not present unless explicitly enabled.

  gofumpt:
    module-path: github.com/mlflow/mlflow-go
    extra-rules: true

  tagliatelle:
    case:
      rules:
        json: snake

issues:
  exclude-files:
    - ".*\\.g\\.go$"
    - ".*\\.pb\\.go$"
