// Code generated by mockery v2.27.1. DO NOT EDIT.

package store

import (
	contract "github.com/mlflow/mlflow-go/pkg/contract"
	mock "github.com/stretchr/testify/mock"

	protos "github.com/mlflow/mlflow-go/pkg/protos"
)

// MockTrackingStore is an autogenerated mock type for the TrackingStore type
type MockTrackingStore struct {
	mock.Mock
}

type MockTrackingStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTrackingStore) EXPECT() *MockTrackingStore_Expecter {
	return &MockTrackingStore_Expecter{mock: &_m.Mock}
}

// CreateExperiment provides a mock function with given fields: input
func (_m *MockTrackingStore) CreateExperiment(input *protos.CreateExperiment) (string, *contract.Error) {
	ret := _m.Called(input)

	var r0 string
	var r1 *contract.Error
	if rf, ok := ret.Get(0).(func(*protos.CreateExperiment) (string, *contract.Error)); ok {
		return rf(input)
	}
	if rf, ok := ret.Get(0).(func(*protos.CreateExperiment) string); ok {
		r0 = rf(input)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(*protos.CreateExperiment) *contract.Error); ok {
		r1 = rf(input)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*contract.Error)
		}
	}

	return r0, r1
}

// MockTrackingStore_CreateExperiment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateExperiment'
type MockTrackingStore_CreateExperiment_Call struct {
	*mock.Call
}

// CreateExperiment is a helper method to define mock.On call
//   - input *protos.CreateExperiment
func (_e *MockTrackingStore_Expecter) CreateExperiment(input interface{}) *MockTrackingStore_CreateExperiment_Call {
	return &MockTrackingStore_CreateExperiment_Call{Call: _e.mock.On("CreateExperiment", input)}
}

func (_c *MockTrackingStore_CreateExperiment_Call) Run(run func(input *protos.CreateExperiment)) *MockTrackingStore_CreateExperiment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*protos.CreateExperiment))
	})
	return _c
}

func (_c *MockTrackingStore_CreateExperiment_Call) Return(_a0 string, _a1 *contract.Error) *MockTrackingStore_CreateExperiment_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTrackingStore_CreateExperiment_Call) RunAndReturn(run func(*protos.CreateExperiment) (string, *contract.Error)) *MockTrackingStore_CreateExperiment_Call {
	_c.Call.Return(run)
	return _c
}

// CreateRun provides a mock function with given fields: input
func (_m *MockTrackingStore) CreateRun(input *protos.CreateRun) (*protos.Run, *contract.Error) {
	ret := _m.Called(input)

	var r0 *protos.Run
	var r1 *contract.Error
	if rf, ok := ret.Get(0).(func(*protos.CreateRun) (*protos.Run, *contract.Error)); ok {
		return rf(input)
	}
	if rf, ok := ret.Get(0).(func(*protos.CreateRun) *protos.Run); ok {
		r0 = rf(input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*protos.Run)
		}
	}

	if rf, ok := ret.Get(1).(func(*protos.CreateRun) *contract.Error); ok {
		r1 = rf(input)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*contract.Error)
		}
	}

	return r0, r1
}

// MockTrackingStore_CreateRun_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRun'
type MockTrackingStore_CreateRun_Call struct {
	*mock.Call
}

// CreateRun is a helper method to define mock.On call
//   - input *protos.CreateRun
func (_e *MockTrackingStore_Expecter) CreateRun(input interface{}) *MockTrackingStore_CreateRun_Call {
	return &MockTrackingStore_CreateRun_Call{Call: _e.mock.On("CreateRun", input)}
}

func (_c *MockTrackingStore_CreateRun_Call) Run(run func(input *protos.CreateRun)) *MockTrackingStore_CreateRun_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*protos.CreateRun))
	})
	return _c
}

func (_c *MockTrackingStore_CreateRun_Call) Return(_a0 *protos.Run, _a1 *contract.Error) *MockTrackingStore_CreateRun_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTrackingStore_CreateRun_Call) RunAndReturn(run func(*protos.CreateRun) (*protos.Run, *contract.Error)) *MockTrackingStore_CreateRun_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteExperiment provides a mock function with given fields: id
func (_m *MockTrackingStore) DeleteExperiment(id string) *contract.Error {
	ret := _m.Called(id)

	var r0 *contract.Error
	if rf, ok := ret.Get(0).(func(string) *contract.Error); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*contract.Error)
		}
	}

	return r0
}

// MockTrackingStore_DeleteExperiment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteExperiment'
type MockTrackingStore_DeleteExperiment_Call struct {
	*mock.Call
}

// DeleteExperiment is a helper method to define mock.On call
//   - id string
func (_e *MockTrackingStore_Expecter) DeleteExperiment(id interface{}) *MockTrackingStore_DeleteExperiment_Call {
	return &MockTrackingStore_DeleteExperiment_Call{Call: _e.mock.On("DeleteExperiment", id)}
}

func (_c *MockTrackingStore_DeleteExperiment_Call) Run(run func(id string)) *MockTrackingStore_DeleteExperiment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockTrackingStore_DeleteExperiment_Call) Return(_a0 *contract.Error) *MockTrackingStore_DeleteExperiment_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTrackingStore_DeleteExperiment_Call) RunAndReturn(run func(string) *contract.Error) *MockTrackingStore_DeleteExperiment_Call {
	_c.Call.Return(run)
	return _c
}

// GetExperiment provides a mock function with given fields: id
func (_m *MockTrackingStore) GetExperiment(id string) (*protos.Experiment, *contract.Error) {
	ret := _m.Called(id)

	var r0 *protos.Experiment
	var r1 *contract.Error
	if rf, ok := ret.Get(0).(func(string) (*protos.Experiment, *contract.Error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *protos.Experiment); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*protos.Experiment)
		}
	}

	if rf, ok := ret.Get(1).(func(string) *contract.Error); ok {
		r1 = rf(id)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*contract.Error)
		}
	}

	return r0, r1
}

// MockTrackingStore_GetExperiment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExperiment'
type MockTrackingStore_GetExperiment_Call struct {
	*mock.Call
}

// GetExperiment is a helper method to define mock.On call
//   - id string
func (_e *MockTrackingStore_Expecter) GetExperiment(id interface{}) *MockTrackingStore_GetExperiment_Call {
	return &MockTrackingStore_GetExperiment_Call{Call: _e.mock.On("GetExperiment", id)}
}

func (_c *MockTrackingStore_GetExperiment_Call) Run(run func(id string)) *MockTrackingStore_GetExperiment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockTrackingStore_GetExperiment_Call) Return(_a0 *protos.Experiment, _a1 *contract.Error) *MockTrackingStore_GetExperiment_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTrackingStore_GetExperiment_Call) RunAndReturn(run func(string) (*protos.Experiment, *contract.Error)) *MockTrackingStore_GetExperiment_Call {
	_c.Call.Return(run)
	return _c
}

// GetExperimentByName provides a mock function with given fields: name
func (_m *MockTrackingStore) GetExperimentByName(name string) (*protos.Experiment, *contract.Error) {
	ret := _m.Called(name)

	var r0 *protos.Experiment
	var r1 *contract.Error
	if rf, ok := ret.Get(0).(func(string) (*protos.Experiment, *contract.Error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) *protos.Experiment); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*protos.Experiment)
		}
	}

	if rf, ok := ret.Get(1).(func(string) *contract.Error); ok {
		r1 = rf(name)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*contract.Error)
		}
	}

	return r0, r1
}

// MockTrackingStore_GetExperimentByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExperimentByName'
type MockTrackingStore_GetExperimentByName_Call struct {
	*mock.Call
}

// GetExperimentByName is a helper method to define mock.On call
//   - name string
func (_e *MockTrackingStore_Expecter) GetExperimentByName(name interface{}) *MockTrackingStore_GetExperimentByName_Call {
	return &MockTrackingStore_GetExperimentByName_Call{Call: _e.mock.On("GetExperimentByName", name)}
}

func (_c *MockTrackingStore_GetExperimentByName_Call) Run(run func(name string)) *MockTrackingStore_GetExperimentByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockTrackingStore_GetExperimentByName_Call) Return(_a0 *protos.Experiment, _a1 *contract.Error) *MockTrackingStore_GetExperimentByName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTrackingStore_GetExperimentByName_Call) RunAndReturn(run func(string) (*protos.Experiment, *contract.Error)) *MockTrackingStore_GetExperimentByName_Call {
	_c.Call.Return(run)
	return _c
}

// LogBatch provides a mock function with given fields: runID, metrics, params, tags
func (_m *MockTrackingStore) LogBatch(runID string, metrics []*protos.Metric, params []*protos.Param, tags []*protos.RunTag) *contract.Error {
	ret := _m.Called(runID, metrics, params, tags)

	var r0 *contract.Error
	if rf, ok := ret.Get(0).(func(string, []*protos.Metric, []*protos.Param, []*protos.RunTag) *contract.Error); ok {
		r0 = rf(runID, metrics, params, tags)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*contract.Error)
		}
	}

	return r0
}

// MockTrackingStore_LogBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LogBatch'
type MockTrackingStore_LogBatch_Call struct {
	*mock.Call
}

// LogBatch is a helper method to define mock.On call
//   - runID string
//   - metrics []*protos.Metric
//   - params []*protos.Param
//   - tags []*protos.RunTag
func (_e *MockTrackingStore_Expecter) LogBatch(runID interface{}, metrics interface{}, params interface{}, tags interface{}) *MockTrackingStore_LogBatch_Call {
	return &MockTrackingStore_LogBatch_Call{Call: _e.mock.On("LogBatch", runID, metrics, params, tags)}
}

func (_c *MockTrackingStore_LogBatch_Call) Run(run func(runID string, metrics []*protos.Metric, params []*protos.Param, tags []*protos.RunTag)) *MockTrackingStore_LogBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].([]*protos.Metric), args[2].([]*protos.Param), args[3].([]*protos.RunTag))
	})
	return _c
}

func (_c *MockTrackingStore_LogBatch_Call) Return(_a0 *contract.Error) *MockTrackingStore_LogBatch_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTrackingStore_LogBatch_Call) RunAndReturn(run func(string, []*protos.Metric, []*protos.Param, []*protos.RunTag) *contract.Error) *MockTrackingStore_LogBatch_Call {
	_c.Call.Return(run)
	return _c
}

// RestoreExperiment provides a mock function with given fields: id
func (_m *MockTrackingStore) RestoreExperiment(id string) *contract.Error {
	ret := _m.Called(id)

	var r0 *contract.Error
	if rf, ok := ret.Get(0).(func(string) *contract.Error); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*contract.Error)
		}
	}

	return r0
}

// MockTrackingStore_RestoreExperiment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RestoreExperiment'
type MockTrackingStore_RestoreExperiment_Call struct {
	*mock.Call
}

// RestoreExperiment is a helper method to define mock.On call
//   - id string
func (_e *MockTrackingStore_Expecter) RestoreExperiment(id interface{}) *MockTrackingStore_RestoreExperiment_Call {
	return &MockTrackingStore_RestoreExperiment_Call{Call: _e.mock.On("RestoreExperiment", id)}
}

func (_c *MockTrackingStore_RestoreExperiment_Call) Run(run func(id string)) *MockTrackingStore_RestoreExperiment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockTrackingStore_RestoreExperiment_Call) Return(_a0 *contract.Error) *MockTrackingStore_RestoreExperiment_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTrackingStore_RestoreExperiment_Call) RunAndReturn(run func(string) *contract.Error) *MockTrackingStore_RestoreExperiment_Call {
	_c.Call.Return(run)
	return _c
}

// SearchRuns provides a mock function with given fields: experimentIDs, filter, runViewType, maxResults, orderBy, pageToken
func (_m *MockTrackingStore) SearchRuns(experimentIDs []string, filter string, runViewType protos.ViewType, maxResults int, orderBy []string, pageToken string) (*PagedList[*protos.Run], *contract.Error) {
	ret := _m.Called(experimentIDs, filter, runViewType, maxResults, orderBy, pageToken)

	var r0 *PagedList[*protos.Run]
	var r1 *contract.Error
	if rf, ok := ret.Get(0).(func([]string, string, protos.ViewType, int, []string, string) (*PagedList[*protos.Run], *contract.Error)); ok {
		return rf(experimentIDs, filter, runViewType, maxResults, orderBy, pageToken)
	}
	if rf, ok := ret.Get(0).(func([]string, string, protos.ViewType, int, []string, string) *PagedList[*protos.Run]); ok {
		r0 = rf(experimentIDs, filter, runViewType, maxResults, orderBy, pageToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*PagedList[*protos.Run])
		}
	}

	if rf, ok := ret.Get(1).(func([]string, string, protos.ViewType, int, []string, string) *contract.Error); ok {
		r1 = rf(experimentIDs, filter, runViewType, maxResults, orderBy, pageToken)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*contract.Error)
		}
	}

	return r0, r1
}

// MockTrackingStore_SearchRuns_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchRuns'
type MockTrackingStore_SearchRuns_Call struct {
	*mock.Call
}

// SearchRuns is a helper method to define mock.On call
//   - experimentIDs []string
//   - filter string
//   - runViewType protos.ViewType
//   - maxResults int
//   - orderBy []string
//   - pageToken string
func (_e *MockTrackingStore_Expecter) SearchRuns(experimentIDs interface{}, filter interface{}, runViewType interface{}, maxResults interface{}, orderBy interface{}, pageToken interface{}) *MockTrackingStore_SearchRuns_Call {
	return &MockTrackingStore_SearchRuns_Call{Call: _e.mock.On("SearchRuns", experimentIDs, filter, runViewType, maxResults, orderBy, pageToken)}
}

func (_c *MockTrackingStore_SearchRuns_Call) Run(run func(experimentIDs []string, filter string, runViewType protos.ViewType, maxResults int, orderBy []string, pageToken string)) *MockTrackingStore_SearchRuns_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]string), args[1].(string), args[2].(protos.ViewType), args[3].(int), args[4].([]string), args[5].(string))
	})
	return _c
}

func (_c *MockTrackingStore_SearchRuns_Call) Return(pagedList *PagedList[*protos.Run], err *contract.Error) *MockTrackingStore_SearchRuns_Call {
	_c.Call.Return(pagedList, err)
	return _c
}

func (_c *MockTrackingStore_SearchRuns_Call) RunAndReturn(run func([]string, string, protos.ViewType, int, []string, string) (*PagedList[*protos.Run], *contract.Error)) *MockTrackingStore_SearchRuns_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewMockTrackingStore interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockTrackingStore creates a new instance of MockTrackingStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockTrackingStore(t mockConstructorTestingTNewMockTrackingStore) *MockTrackingStore {
	mock := &MockTrackingStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
