// Code generated by mockery v2.46.3. DO NOT EDIT.

package store

import (
	context "context"

	contract "github.com/mlflow/mlflow-go/pkg/contract"
	entities "github.com/mlflow/mlflow-go/pkg/entities"

	mock "github.com/stretchr/testify/mock"

	protos "github.com/mlflow/mlflow-go/pkg/protos"
)

// MockTrackingStore is an autogenerated mock type for the TrackingStore type
type MockTrackingStore struct {
	mock.Mock
}

type MockTrackingStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTrackingStore) EXPECT() *MockTrackingStore_Expecter {
	return &MockTrackingStore_Expecter{mock: &_m.Mock}
}

// CreateExperiment provides a mock function with given fields: ctx, name, artifactLocation, tags
func (_m *MockTrackingStore) CreateExperiment(ctx context.Context, name string, artifactLocation string, tags []*entities.ExperimentTag) (string, *contract.Error) {
	ret := _m.Called(ctx, name, artifactLocation, tags)

	if len(ret) == 0 {
		panic("no return value specified for CreateExperiment")
	}

	var r0 string
	var r1 *contract.Error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, []*entities.ExperimentTag) (string, *contract.Error)); ok {
		return rf(ctx, name, artifactLocation, tags)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, []*entities.ExperimentTag) string); ok {
		r0 = rf(ctx, name, artifactLocation, tags)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, []*entities.ExperimentTag) *contract.Error); ok {
		r1 = rf(ctx, name, artifactLocation, tags)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*contract.Error)
		}
	}

	return r0, r1
}

// MockTrackingStore_CreateExperiment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateExperiment'
type MockTrackingStore_CreateExperiment_Call struct {
	*mock.Call
}

// CreateExperiment is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - artifactLocation string
//   - tags []*entities.ExperimentTag
func (_e *MockTrackingStore_Expecter) CreateExperiment(ctx interface{}, name interface{}, artifactLocation interface{}, tags interface{}) *MockTrackingStore_CreateExperiment_Call {
	return &MockTrackingStore_CreateExperiment_Call{Call: _e.mock.On("CreateExperiment", ctx, name, artifactLocation, tags)}
}

func (_c *MockTrackingStore_CreateExperiment_Call) Run(run func(ctx context.Context, name string, artifactLocation string, tags []*entities.ExperimentTag)) *MockTrackingStore_CreateExperiment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].([]*entities.ExperimentTag))
	})
	return _c
}

func (_c *MockTrackingStore_CreateExperiment_Call) Return(_a0 string, _a1 *contract.Error) *MockTrackingStore_CreateExperiment_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTrackingStore_CreateExperiment_Call) RunAndReturn(run func(context.Context, string, string, []*entities.ExperimentTag) (string, *contract.Error)) *MockTrackingStore_CreateExperiment_Call {
	_c.Call.Return(run)
	return _c
}

// CreateRun provides a mock function with given fields: ctx, experimentID, userID, startTime, tags, runName
func (_m *MockTrackingStore) CreateRun(ctx context.Context, experimentID string, userID string, startTime int64, tags []*entities.RunTag, runName string) (*entities.Run, *contract.Error) {
	ret := _m.Called(ctx, experimentID, userID, startTime, tags, runName)

	if len(ret) == 0 {
		panic("no return value specified for CreateRun")
	}

	var r0 *entities.Run
	var r1 *contract.Error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int64, []*entities.RunTag, string) (*entities.Run, *contract.Error)); ok {
		return rf(ctx, experimentID, userID, startTime, tags, runName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int64, []*entities.RunTag, string) *entities.Run); ok {
		r0 = rf(ctx, experimentID, userID, startTime, tags, runName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Run)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, int64, []*entities.RunTag, string) *contract.Error); ok {
		r1 = rf(ctx, experimentID, userID, startTime, tags, runName)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*contract.Error)
		}
	}

	return r0, r1
}

// MockTrackingStore_CreateRun_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRun'
type MockTrackingStore_CreateRun_Call struct {
	*mock.Call
}

// CreateRun is a helper method to define mock.On call
//   - ctx context.Context
//   - experimentID string
//   - userID string
//   - startTime int64
//   - tags []*entities.RunTag
//   - runName string
func (_e *MockTrackingStore_Expecter) CreateRun(ctx interface{}, experimentID interface{}, userID interface{}, startTime interface{}, tags interface{}, runName interface{}) *MockTrackingStore_CreateRun_Call {
	return &MockTrackingStore_CreateRun_Call{Call: _e.mock.On("CreateRun", ctx, experimentID, userID, startTime, tags, runName)}
}

func (_c *MockTrackingStore_CreateRun_Call) Run(run func(ctx context.Context, experimentID string, userID string, startTime int64, tags []*entities.RunTag, runName string)) *MockTrackingStore_CreateRun_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(int64), args[4].([]*entities.RunTag), args[5].(string))
	})
	return _c
}

func (_c *MockTrackingStore_CreateRun_Call) Return(_a0 *entities.Run, _a1 *contract.Error) *MockTrackingStore_CreateRun_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTrackingStore_CreateRun_Call) RunAndReturn(run func(context.Context, string, string, int64, []*entities.RunTag, string) (*entities.Run, *contract.Error)) *MockTrackingStore_CreateRun_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteExperiment provides a mock function with given fields: ctx, id
func (_m *MockTrackingStore) DeleteExperiment(ctx context.Context, id string) *contract.Error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteExperiment")
	}

	var r0 *contract.Error
	if rf, ok := ret.Get(0).(func(context.Context, string) *contract.Error); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*contract.Error)
		}
	}

	return r0
}

// MockTrackingStore_DeleteExperiment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteExperiment'
type MockTrackingStore_DeleteExperiment_Call struct {
	*mock.Call
}

// DeleteExperiment is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockTrackingStore_Expecter) DeleteExperiment(ctx interface{}, id interface{}) *MockTrackingStore_DeleteExperiment_Call {
	return &MockTrackingStore_DeleteExperiment_Call{Call: _e.mock.On("DeleteExperiment", ctx, id)}
}

func (_c *MockTrackingStore_DeleteExperiment_Call) Run(run func(ctx context.Context, id string)) *MockTrackingStore_DeleteExperiment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTrackingStore_DeleteExperiment_Call) Return(_a0 *contract.Error) *MockTrackingStore_DeleteExperiment_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTrackingStore_DeleteExperiment_Call) RunAndReturn(run func(context.Context, string) *contract.Error) *MockTrackingStore_DeleteExperiment_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRun provides a mock function with given fields: ctx, runID
func (_m *MockTrackingStore) DeleteRun(ctx context.Context, runID string) *contract.Error {
	ret := _m.Called(ctx, runID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRun")
	}

	var r0 *contract.Error
	if rf, ok := ret.Get(0).(func(context.Context, string) *contract.Error); ok {
		r0 = rf(ctx, runID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*contract.Error)
		}
	}

	return r0
}

// MockTrackingStore_DeleteRun_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRun'
type MockTrackingStore_DeleteRun_Call struct {
	*mock.Call
}

// DeleteRun is a helper method to define mock.On call
//   - ctx context.Context
//   - runID string
func (_e *MockTrackingStore_Expecter) DeleteRun(ctx interface{}, runID interface{}) *MockTrackingStore_DeleteRun_Call {
	return &MockTrackingStore_DeleteRun_Call{Call: _e.mock.On("DeleteRun", ctx, runID)}
}

func (_c *MockTrackingStore_DeleteRun_Call) Run(run func(ctx context.Context, runID string)) *MockTrackingStore_DeleteRun_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTrackingStore_DeleteRun_Call) Return(_a0 *contract.Error) *MockTrackingStore_DeleteRun_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTrackingStore_DeleteRun_Call) RunAndReturn(run func(context.Context, string) *contract.Error) *MockTrackingStore_DeleteRun_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTag provides a mock function with given fields: ctx, runID, key
func (_m *MockTrackingStore) DeleteTag(ctx context.Context, runID string, key string) *contract.Error {
	ret := _m.Called(ctx, runID, key)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTag")
	}

	var r0 *contract.Error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *contract.Error); ok {
		r0 = rf(ctx, runID, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*contract.Error)
		}
	}

	return r0
}

// MockTrackingStore_DeleteTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTag'
type MockTrackingStore_DeleteTag_Call struct {
	*mock.Call
}

// DeleteTag is a helper method to define mock.On call
//   - ctx context.Context
//   - runID string
//   - key string
func (_e *MockTrackingStore_Expecter) DeleteTag(ctx interface{}, runID interface{}, key interface{}) *MockTrackingStore_DeleteTag_Call {
	return &MockTrackingStore_DeleteTag_Call{Call: _e.mock.On("DeleteTag", ctx, runID, key)}
}

func (_c *MockTrackingStore_DeleteTag_Call) Run(run func(ctx context.Context, runID string, key string)) *MockTrackingStore_DeleteTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockTrackingStore_DeleteTag_Call) Return(_a0 *contract.Error) *MockTrackingStore_DeleteTag_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTrackingStore_DeleteTag_Call) RunAndReturn(run func(context.Context, string, string) *contract.Error) *MockTrackingStore_DeleteTag_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTraceTag provides a mock function with given fields: ctx, tag
func (_m *MockTrackingStore) DeleteTraceTag(ctx context.Context, tag *entities.TraceTag) *contract.Error {
	ret := _m.Called(ctx, tag)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTraceTag")
	}

	var r0 *contract.Error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.TraceTag) *contract.Error); ok {
		r0 = rf(ctx, tag)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*contract.Error)
		}
	}

	return r0
}

// MockTrackingStore_DeleteTraceTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTraceTag'
type MockTrackingStore_DeleteTraceTag_Call struct {
	*mock.Call
}

// DeleteTraceTag is a helper method to define mock.On call
//   - ctx context.Context
//   - tag *entities.TraceTag
func (_e *MockTrackingStore_Expecter) DeleteTraceTag(ctx interface{}, tag interface{}) *MockTrackingStore_DeleteTraceTag_Call {
	return &MockTrackingStore_DeleteTraceTag_Call{Call: _e.mock.On("DeleteTraceTag", ctx, tag)}
}

func (_c *MockTrackingStore_DeleteTraceTag_Call) Run(run func(ctx context.Context, tag *entities.TraceTag)) *MockTrackingStore_DeleteTraceTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.TraceTag))
	})
	return _c
}

func (_c *MockTrackingStore_DeleteTraceTag_Call) Return(_a0 *contract.Error) *MockTrackingStore_DeleteTraceTag_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTrackingStore_DeleteTraceTag_Call) RunAndReturn(run func(context.Context, *entities.TraceTag) *contract.Error) *MockTrackingStore_DeleteTraceTag_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTraces provides a mock function with given fields: ctx, experimentId, maxTimestampMillis, maxTraces, requestIds
func (_m *MockTrackingStore) DeleteTraces(ctx context.Context, experimentId string, maxTimestampMillis int64, maxTraces int32, requestIds []string) (int32, *contract.Error) {
	ret := _m.Called(ctx, experimentId, maxTimestampMillis, maxTraces, requestIds)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTraces")
	}

	var r0 int32
	var r1 *contract.Error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, int32, []string) (int32, *contract.Error)); ok {
		return rf(ctx, experimentId, maxTimestampMillis, maxTraces, requestIds)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, int32, []string) int32); ok {
		r0 = rf(ctx, experimentId, maxTimestampMillis, maxTraces, requestIds)
	} else {
		r0 = ret.Get(0).(int32)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int64, int32, []string) *contract.Error); ok {
		r1 = rf(ctx, experimentId, maxTimestampMillis, maxTraces, requestIds)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*contract.Error)
		}
	}

	return r0, r1
}

// MockTrackingStore_DeleteTraces_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTraces'
type MockTrackingStore_DeleteTraces_Call struct {
	*mock.Call
}

// DeleteTraces is a helper method to define mock.On call
//   - ctx context.Context
//   - experimentId string
//   - maxTimestampMillis int64
//   - maxTraces int32
//   - requestIds []string
func (_e *MockTrackingStore_Expecter) DeleteTraces(ctx interface{}, experimentId interface{}, maxTimestampMillis interface{}, maxTraces interface{}, requestIds interface{}) *MockTrackingStore_DeleteTraces_Call {
	return &MockTrackingStore_DeleteTraces_Call{Call: _e.mock.On("DeleteTraces", ctx, experimentId, maxTimestampMillis, maxTraces, requestIds)}
}

func (_c *MockTrackingStore_DeleteTraces_Call) Run(run func(ctx context.Context, experimentId string, maxTimestampMillis int64, maxTraces int32, requestIds []string)) *MockTrackingStore_DeleteTraces_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int64), args[3].(int32), args[4].([]string))
	})
	return _c
}

func (_c *MockTrackingStore_DeleteTraces_Call) Return(_a0 int32, _a1 *contract.Error) *MockTrackingStore_DeleteTraces_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTrackingStore_DeleteTraces_Call) RunAndReturn(run func(context.Context, string, int64, int32, []string) (int32, *contract.Error)) *MockTrackingStore_DeleteTraces_Call {
	_c.Call.Return(run)
	return _c
}

// Destroy provides a mock function with given fields:
func (_m *MockTrackingStore) Destroy() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Destroy")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTrackingStore_Destroy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Destroy'
type MockTrackingStore_Destroy_Call struct {
	*mock.Call
}

// Destroy is a helper method to define mock.On call
func (_e *MockTrackingStore_Expecter) Destroy() *MockTrackingStore_Destroy_Call {
	return &MockTrackingStore_Destroy_Call{Call: _e.mock.On("Destroy")}
}

func (_c *MockTrackingStore_Destroy_Call) Run(run func()) *MockTrackingStore_Destroy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTrackingStore_Destroy_Call) Return(_a0 error) *MockTrackingStore_Destroy_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTrackingStore_Destroy_Call) RunAndReturn(run func() error) *MockTrackingStore_Destroy_Call {
	_c.Call.Return(run)
	return _c
}

// EndTrace provides a mock function with given fields: ctx, reqeustID, timestampMS, status, metadata, tags
func (_m *MockTrackingStore) EndTrace(ctx context.Context, reqeustID string, timestampMS int64, status string, metadata []*entities.TraceRequestMetadata, tags []*entities.TraceTag) (*entities.TraceInfo, error) {
	ret := _m.Called(ctx, reqeustID, timestampMS, status, metadata, tags)

	if len(ret) == 0 {
		panic("no return value specified for EndTrace")
	}

	var r0 *entities.TraceInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, string, []*entities.TraceRequestMetadata, []*entities.TraceTag) (*entities.TraceInfo, error)); ok {
		return rf(ctx, reqeustID, timestampMS, status, metadata, tags)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, string, []*entities.TraceRequestMetadata, []*entities.TraceTag) *entities.TraceInfo); ok {
		r0 = rf(ctx, reqeustID, timestampMS, status, metadata, tags)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.TraceInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int64, string, []*entities.TraceRequestMetadata, []*entities.TraceTag) error); ok {
		r1 = rf(ctx, reqeustID, timestampMS, status, metadata, tags)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTrackingStore_EndTrace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EndTrace'
type MockTrackingStore_EndTrace_Call struct {
	*mock.Call
}

// EndTrace is a helper method to define mock.On call
//   - ctx context.Context
//   - reqeustID string
//   - timestampMS int64
//   - status string
//   - metadata []*entities.TraceRequestMetadata
//   - tags []*entities.TraceTag
func (_e *MockTrackingStore_Expecter) EndTrace(ctx interface{}, reqeustID interface{}, timestampMS interface{}, status interface{}, metadata interface{}, tags interface{}) *MockTrackingStore_EndTrace_Call {
	return &MockTrackingStore_EndTrace_Call{Call: _e.mock.On("EndTrace", ctx, reqeustID, timestampMS, status, metadata, tags)}
}

func (_c *MockTrackingStore_EndTrace_Call) Run(run func(ctx context.Context, reqeustID string, timestampMS int64, status string, metadata []*entities.TraceRequestMetadata, tags []*entities.TraceTag)) *MockTrackingStore_EndTrace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int64), args[3].(string), args[4].([]*entities.TraceRequestMetadata), args[5].([]*entities.TraceTag))
	})
	return _c
}

func (_c *MockTrackingStore_EndTrace_Call) Return(_a0 *entities.TraceInfo, _a1 error) *MockTrackingStore_EndTrace_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTrackingStore_EndTrace_Call) RunAndReturn(run func(context.Context, string, int64, string, []*entities.TraceRequestMetadata, []*entities.TraceTag) (*entities.TraceInfo, error)) *MockTrackingStore_EndTrace_Call {
	_c.Call.Return(run)
	return _c
}

// GetExperiment provides a mock function with given fields: ctx, id
func (_m *MockTrackingStore) GetExperiment(ctx context.Context, id string) (*entities.Experiment, *contract.Error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetExperiment")
	}

	var r0 *entities.Experiment
	var r1 *contract.Error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entities.Experiment, *contract.Error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entities.Experiment); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Experiment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) *contract.Error); ok {
		r1 = rf(ctx, id)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*contract.Error)
		}
	}

	return r0, r1
}

// MockTrackingStore_GetExperiment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExperiment'
type MockTrackingStore_GetExperiment_Call struct {
	*mock.Call
}

// GetExperiment is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockTrackingStore_Expecter) GetExperiment(ctx interface{}, id interface{}) *MockTrackingStore_GetExperiment_Call {
	return &MockTrackingStore_GetExperiment_Call{Call: _e.mock.On("GetExperiment", ctx, id)}
}

func (_c *MockTrackingStore_GetExperiment_Call) Run(run func(ctx context.Context, id string)) *MockTrackingStore_GetExperiment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTrackingStore_GetExperiment_Call) Return(_a0 *entities.Experiment, _a1 *contract.Error) *MockTrackingStore_GetExperiment_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTrackingStore_GetExperiment_Call) RunAndReturn(run func(context.Context, string) (*entities.Experiment, *contract.Error)) *MockTrackingStore_GetExperiment_Call {
	_c.Call.Return(run)
	return _c
}

// GetExperimentByName provides a mock function with given fields: ctx, name
func (_m *MockTrackingStore) GetExperimentByName(ctx context.Context, name string) (*entities.Experiment, *contract.Error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetExperimentByName")
	}

	var r0 *entities.Experiment
	var r1 *contract.Error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entities.Experiment, *contract.Error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entities.Experiment); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Experiment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) *contract.Error); ok {
		r1 = rf(ctx, name)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*contract.Error)
		}
	}

	return r0, r1
}

// MockTrackingStore_GetExperimentByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExperimentByName'
type MockTrackingStore_GetExperimentByName_Call struct {
	*mock.Call
}

// GetExperimentByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockTrackingStore_Expecter) GetExperimentByName(ctx interface{}, name interface{}) *MockTrackingStore_GetExperimentByName_Call {
	return &MockTrackingStore_GetExperimentByName_Call{Call: _e.mock.On("GetExperimentByName", ctx, name)}
}

func (_c *MockTrackingStore_GetExperimentByName_Call) Run(run func(ctx context.Context, name string)) *MockTrackingStore_GetExperimentByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTrackingStore_GetExperimentByName_Call) Return(_a0 *entities.Experiment, _a1 *contract.Error) *MockTrackingStore_GetExperimentByName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTrackingStore_GetExperimentByName_Call) RunAndReturn(run func(context.Context, string) (*entities.Experiment, *contract.Error)) *MockTrackingStore_GetExperimentByName_Call {
	_c.Call.Return(run)
	return _c
}

// GetRun provides a mock function with given fields: ctx, runID
func (_m *MockTrackingStore) GetRun(ctx context.Context, runID string) (*entities.Run, *contract.Error) {
	ret := _m.Called(ctx, runID)

	if len(ret) == 0 {
		panic("no return value specified for GetRun")
	}

	var r0 *entities.Run
	var r1 *contract.Error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entities.Run, *contract.Error)); ok {
		return rf(ctx, runID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entities.Run); ok {
		r0 = rf(ctx, runID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Run)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) *contract.Error); ok {
		r1 = rf(ctx, runID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*contract.Error)
		}
	}

	return r0, r1
}

// MockTrackingStore_GetRun_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRun'
type MockTrackingStore_GetRun_Call struct {
	*mock.Call
}

// GetRun is a helper method to define mock.On call
//   - ctx context.Context
//   - runID string
func (_e *MockTrackingStore_Expecter) GetRun(ctx interface{}, runID interface{}) *MockTrackingStore_GetRun_Call {
	return &MockTrackingStore_GetRun_Call{Call: _e.mock.On("GetRun", ctx, runID)}
}

func (_c *MockTrackingStore_GetRun_Call) Run(run func(ctx context.Context, runID string)) *MockTrackingStore_GetRun_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTrackingStore_GetRun_Call) Return(_a0 *entities.Run, _a1 *contract.Error) *MockTrackingStore_GetRun_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTrackingStore_GetRun_Call) RunAndReturn(run func(context.Context, string) (*entities.Run, *contract.Error)) *MockTrackingStore_GetRun_Call {
	_c.Call.Return(run)
	return _c
}

// GetRunTag provides a mock function with given fields: ctx, runID, tagKey
func (_m *MockTrackingStore) GetRunTag(ctx context.Context, runID string, tagKey string) (*entities.RunTag, *contract.Error) {
	ret := _m.Called(ctx, runID, tagKey)

	if len(ret) == 0 {
		panic("no return value specified for GetRunTag")
	}

	var r0 *entities.RunTag
	var r1 *contract.Error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*entities.RunTag, *contract.Error)); ok {
		return rf(ctx, runID, tagKey)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *entities.RunTag); ok {
		r0 = rf(ctx, runID, tagKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.RunTag)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) *contract.Error); ok {
		r1 = rf(ctx, runID, tagKey)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*contract.Error)
		}
	}

	return r0, r1
}

// MockTrackingStore_GetRunTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRunTag'
type MockTrackingStore_GetRunTag_Call struct {
	*mock.Call
}

// GetRunTag is a helper method to define mock.On call
//   - ctx context.Context
//   - runID string
//   - tagKey string
func (_e *MockTrackingStore_Expecter) GetRunTag(ctx interface{}, runID interface{}, tagKey interface{}) *MockTrackingStore_GetRunTag_Call {
	return &MockTrackingStore_GetRunTag_Call{Call: _e.mock.On("GetRunTag", ctx, runID, tagKey)}
}

func (_c *MockTrackingStore_GetRunTag_Call) Run(run func(ctx context.Context, runID string, tagKey string)) *MockTrackingStore_GetRunTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockTrackingStore_GetRunTag_Call) Return(_a0 *entities.RunTag, _a1 *contract.Error) *MockTrackingStore_GetRunTag_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTrackingStore_GetRunTag_Call) RunAndReturn(run func(context.Context, string, string) (*entities.RunTag, *contract.Error)) *MockTrackingStore_GetRunTag_Call {
	_c.Call.Return(run)
	return _c
}

// GetTraceInfo provides a mock function with given fields: ctx, reqeustID
func (_m *MockTrackingStore) GetTraceInfo(ctx context.Context, reqeustID string) (*entities.TraceInfo, *contract.Error) {
	ret := _m.Called(ctx, reqeustID)

	if len(ret) == 0 {
		panic("no return value specified for GetTraceInfo")
	}

	var r0 *entities.TraceInfo
	var r1 *contract.Error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entities.TraceInfo, *contract.Error)); ok {
		return rf(ctx, reqeustID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entities.TraceInfo); ok {
		r0 = rf(ctx, reqeustID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.TraceInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) *contract.Error); ok {
		r1 = rf(ctx, reqeustID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*contract.Error)
		}
	}

	return r0, r1
}

// MockTrackingStore_GetTraceInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTraceInfo'
type MockTrackingStore_GetTraceInfo_Call struct {
	*mock.Call
}

// GetTraceInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - reqeustID string
func (_e *MockTrackingStore_Expecter) GetTraceInfo(ctx interface{}, reqeustID interface{}) *MockTrackingStore_GetTraceInfo_Call {
	return &MockTrackingStore_GetTraceInfo_Call{Call: _e.mock.On("GetTraceInfo", ctx, reqeustID)}
}

func (_c *MockTrackingStore_GetTraceInfo_Call) Run(run func(ctx context.Context, reqeustID string)) *MockTrackingStore_GetTraceInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTrackingStore_GetTraceInfo_Call) Return(_a0 *entities.TraceInfo, _a1 *contract.Error) *MockTrackingStore_GetTraceInfo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTrackingStore_GetTraceInfo_Call) RunAndReturn(run func(context.Context, string) (*entities.TraceInfo, *contract.Error)) *MockTrackingStore_GetTraceInfo_Call {
	_c.Call.Return(run)
	return _c
}

// GetTraceTag provides a mock function with given fields: ctx, requestID, key
func (_m *MockTrackingStore) GetTraceTag(ctx context.Context, requestID string, key string) (*entities.TraceTag, *contract.Error) {
	ret := _m.Called(ctx, requestID, key)

	if len(ret) == 0 {
		panic("no return value specified for GetTraceTag")
	}

	var r0 *entities.TraceTag
	var r1 *contract.Error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*entities.TraceTag, *contract.Error)); ok {
		return rf(ctx, requestID, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *entities.TraceTag); ok {
		r0 = rf(ctx, requestID, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.TraceTag)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) *contract.Error); ok {
		r1 = rf(ctx, requestID, key)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*contract.Error)
		}
	}

	return r0, r1
}

// MockTrackingStore_GetTraceTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTraceTag'
type MockTrackingStore_GetTraceTag_Call struct {
	*mock.Call
}

// GetTraceTag is a helper method to define mock.On call
//   - ctx context.Context
//   - requestID string
//   - key string
func (_e *MockTrackingStore_Expecter) GetTraceTag(ctx interface{}, requestID interface{}, key interface{}) *MockTrackingStore_GetTraceTag_Call {
	return &MockTrackingStore_GetTraceTag_Call{Call: _e.mock.On("GetTraceTag", ctx, requestID, key)}
}

func (_c *MockTrackingStore_GetTraceTag_Call) Run(run func(ctx context.Context, requestID string, key string)) *MockTrackingStore_GetTraceTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockTrackingStore_GetTraceTag_Call) Return(_a0 *entities.TraceTag, _a1 *contract.Error) *MockTrackingStore_GetTraceTag_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTrackingStore_GetTraceTag_Call) RunAndReturn(run func(context.Context, string, string) (*entities.TraceTag, *contract.Error)) *MockTrackingStore_GetTraceTag_Call {
	_c.Call.Return(run)
	return _c
}

// LogBatch provides a mock function with given fields: ctx, runID, metrics, params, tags
func (_m *MockTrackingStore) LogBatch(ctx context.Context, runID string, metrics []*entities.Metric, params []*entities.Param, tags []*entities.RunTag) *contract.Error {
	ret := _m.Called(ctx, runID, metrics, params, tags)

	if len(ret) == 0 {
		panic("no return value specified for LogBatch")
	}

	var r0 *contract.Error
	if rf, ok := ret.Get(0).(func(context.Context, string, []*entities.Metric, []*entities.Param, []*entities.RunTag) *contract.Error); ok {
		r0 = rf(ctx, runID, metrics, params, tags)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*contract.Error)
		}
	}

	return r0
}

// MockTrackingStore_LogBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LogBatch'
type MockTrackingStore_LogBatch_Call struct {
	*mock.Call
}

// LogBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - runID string
//   - metrics []*entities.Metric
//   - params []*entities.Param
//   - tags []*entities.RunTag
func (_e *MockTrackingStore_Expecter) LogBatch(ctx interface{}, runID interface{}, metrics interface{}, params interface{}, tags interface{}) *MockTrackingStore_LogBatch_Call {
	return &MockTrackingStore_LogBatch_Call{Call: _e.mock.On("LogBatch", ctx, runID, metrics, params, tags)}
}

func (_c *MockTrackingStore_LogBatch_Call) Run(run func(ctx context.Context, runID string, metrics []*entities.Metric, params []*entities.Param, tags []*entities.RunTag)) *MockTrackingStore_LogBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]*entities.Metric), args[3].([]*entities.Param), args[4].([]*entities.RunTag))
	})
	return _c
}

func (_c *MockTrackingStore_LogBatch_Call) Return(_a0 *contract.Error) *MockTrackingStore_LogBatch_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTrackingStore_LogBatch_Call) RunAndReturn(run func(context.Context, string, []*entities.Metric, []*entities.Param, []*entities.RunTag) *contract.Error) *MockTrackingStore_LogBatch_Call {
	_c.Call.Return(run)
	return _c
}

// LogInputs provides a mock function with given fields: ctx, runID, datasets
func (_m *MockTrackingStore) LogInputs(ctx context.Context, runID string, datasets []*entities.DatasetInput) *contract.Error {
	ret := _m.Called(ctx, runID, datasets)

	if len(ret) == 0 {
		panic("no return value specified for LogInputs")
	}

	var r0 *contract.Error
	if rf, ok := ret.Get(0).(func(context.Context, string, []*entities.DatasetInput) *contract.Error); ok {
		r0 = rf(ctx, runID, datasets)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*contract.Error)
		}
	}

	return r0
}

// MockTrackingStore_LogInputs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LogInputs'
type MockTrackingStore_LogInputs_Call struct {
	*mock.Call
}

// LogInputs is a helper method to define mock.On call
//   - ctx context.Context
//   - runID string
//   - datasets []*entities.DatasetInput
func (_e *MockTrackingStore_Expecter) LogInputs(ctx interface{}, runID interface{}, datasets interface{}) *MockTrackingStore_LogInputs_Call {
	return &MockTrackingStore_LogInputs_Call{Call: _e.mock.On("LogInputs", ctx, runID, datasets)}
}

func (_c *MockTrackingStore_LogInputs_Call) Run(run func(ctx context.Context, runID string, datasets []*entities.DatasetInput)) *MockTrackingStore_LogInputs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]*entities.DatasetInput))
	})
	return _c
}

func (_c *MockTrackingStore_LogInputs_Call) Return(_a0 *contract.Error) *MockTrackingStore_LogInputs_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTrackingStore_LogInputs_Call) RunAndReturn(run func(context.Context, string, []*entities.DatasetInput) *contract.Error) *MockTrackingStore_LogInputs_Call {
	_c.Call.Return(run)
	return _c
}

// LogMetric provides a mock function with given fields: ctx, runID, metric
func (_m *MockTrackingStore) LogMetric(ctx context.Context, runID string, metric *entities.Metric) *contract.Error {
	ret := _m.Called(ctx, runID, metric)

	if len(ret) == 0 {
		panic("no return value specified for LogMetric")
	}

	var r0 *contract.Error
	if rf, ok := ret.Get(0).(func(context.Context, string, *entities.Metric) *contract.Error); ok {
		r0 = rf(ctx, runID, metric)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*contract.Error)
		}
	}

	return r0
}

// MockTrackingStore_LogMetric_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LogMetric'
type MockTrackingStore_LogMetric_Call struct {
	*mock.Call
}

// LogMetric is a helper method to define mock.On call
//   - ctx context.Context
//   - runID string
//   - metric *entities.Metric
func (_e *MockTrackingStore_Expecter) LogMetric(ctx interface{}, runID interface{}, metric interface{}) *MockTrackingStore_LogMetric_Call {
	return &MockTrackingStore_LogMetric_Call{Call: _e.mock.On("LogMetric", ctx, runID, metric)}
}

func (_c *MockTrackingStore_LogMetric_Call) Run(run func(ctx context.Context, runID string, metric *entities.Metric)) *MockTrackingStore_LogMetric_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*entities.Metric))
	})
	return _c
}

func (_c *MockTrackingStore_LogMetric_Call) Return(_a0 *contract.Error) *MockTrackingStore_LogMetric_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTrackingStore_LogMetric_Call) RunAndReturn(run func(context.Context, string, *entities.Metric) *contract.Error) *MockTrackingStore_LogMetric_Call {
	_c.Call.Return(run)
	return _c
}

// LogParam provides a mock function with given fields: ctx, runID, metric
func (_m *MockTrackingStore) LogParam(ctx context.Context, runID string, metric *entities.Param) *contract.Error {
	ret := _m.Called(ctx, runID, metric)

	if len(ret) == 0 {
		panic("no return value specified for LogParam")
	}

	var r0 *contract.Error
	if rf, ok := ret.Get(0).(func(context.Context, string, *entities.Param) *contract.Error); ok {
		r0 = rf(ctx, runID, metric)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*contract.Error)
		}
	}

	return r0
}

// MockTrackingStore_LogParam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LogParam'
type MockTrackingStore_LogParam_Call struct {
	*mock.Call
}

// LogParam is a helper method to define mock.On call
//   - ctx context.Context
//   - runID string
//   - metric *entities.Param
func (_e *MockTrackingStore_Expecter) LogParam(ctx interface{}, runID interface{}, metric interface{}) *MockTrackingStore_LogParam_Call {
	return &MockTrackingStore_LogParam_Call{Call: _e.mock.On("LogParam", ctx, runID, metric)}
}

func (_c *MockTrackingStore_LogParam_Call) Run(run func(ctx context.Context, runID string, metric *entities.Param)) *MockTrackingStore_LogParam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*entities.Param))
	})
	return _c
}

func (_c *MockTrackingStore_LogParam_Call) Return(_a0 *contract.Error) *MockTrackingStore_LogParam_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTrackingStore_LogParam_Call) RunAndReturn(run func(context.Context, string, *entities.Param) *contract.Error) *MockTrackingStore_LogParam_Call {
	_c.Call.Return(run)
	return _c
}

// RenameExperiment provides a mock function with given fields: ctx, experimentID, name
func (_m *MockTrackingStore) RenameExperiment(ctx context.Context, experimentID string, name string) *contract.Error {
	ret := _m.Called(ctx, experimentID, name)

	if len(ret) == 0 {
		panic("no return value specified for RenameExperiment")
	}

	var r0 *contract.Error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *contract.Error); ok {
		r0 = rf(ctx, experimentID, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*contract.Error)
		}
	}

	return r0
}

// MockTrackingStore_RenameExperiment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RenameExperiment'
type MockTrackingStore_RenameExperiment_Call struct {
	*mock.Call
}

// RenameExperiment is a helper method to define mock.On call
//   - ctx context.Context
//   - experimentID string
//   - name string
func (_e *MockTrackingStore_Expecter) RenameExperiment(ctx interface{}, experimentID interface{}, name interface{}) *MockTrackingStore_RenameExperiment_Call {
	return &MockTrackingStore_RenameExperiment_Call{Call: _e.mock.On("RenameExperiment", ctx, experimentID, name)}
}

func (_c *MockTrackingStore_RenameExperiment_Call) Run(run func(ctx context.Context, experimentID string, name string)) *MockTrackingStore_RenameExperiment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockTrackingStore_RenameExperiment_Call) Return(_a0 *contract.Error) *MockTrackingStore_RenameExperiment_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTrackingStore_RenameExperiment_Call) RunAndReturn(run func(context.Context, string, string) *contract.Error) *MockTrackingStore_RenameExperiment_Call {
	_c.Call.Return(run)
	return _c
}

// RestoreExperiment provides a mock function with given fields: ctx, id
func (_m *MockTrackingStore) RestoreExperiment(ctx context.Context, id string) *contract.Error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for RestoreExperiment")
	}

	var r0 *contract.Error
	if rf, ok := ret.Get(0).(func(context.Context, string) *contract.Error); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*contract.Error)
		}
	}

	return r0
}

// MockTrackingStore_RestoreExperiment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RestoreExperiment'
type MockTrackingStore_RestoreExperiment_Call struct {
	*mock.Call
}

// RestoreExperiment is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockTrackingStore_Expecter) RestoreExperiment(ctx interface{}, id interface{}) *MockTrackingStore_RestoreExperiment_Call {
	return &MockTrackingStore_RestoreExperiment_Call{Call: _e.mock.On("RestoreExperiment", ctx, id)}
}

func (_c *MockTrackingStore_RestoreExperiment_Call) Run(run func(ctx context.Context, id string)) *MockTrackingStore_RestoreExperiment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTrackingStore_RestoreExperiment_Call) Return(_a0 *contract.Error) *MockTrackingStore_RestoreExperiment_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTrackingStore_RestoreExperiment_Call) RunAndReturn(run func(context.Context, string) *contract.Error) *MockTrackingStore_RestoreExperiment_Call {
	_c.Call.Return(run)
	return _c
}

// RestoreRun provides a mock function with given fields: ctx, runID
func (_m *MockTrackingStore) RestoreRun(ctx context.Context, runID string) *contract.Error {
	ret := _m.Called(ctx, runID)

	if len(ret) == 0 {
		panic("no return value specified for RestoreRun")
	}

	var r0 *contract.Error
	if rf, ok := ret.Get(0).(func(context.Context, string) *contract.Error); ok {
		r0 = rf(ctx, runID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*contract.Error)
		}
	}

	return r0
}

// MockTrackingStore_RestoreRun_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RestoreRun'
type MockTrackingStore_RestoreRun_Call struct {
	*mock.Call
}

// RestoreRun is a helper method to define mock.On call
//   - ctx context.Context
//   - runID string
func (_e *MockTrackingStore_Expecter) RestoreRun(ctx interface{}, runID interface{}) *MockTrackingStore_RestoreRun_Call {
	return &MockTrackingStore_RestoreRun_Call{Call: _e.mock.On("RestoreRun", ctx, runID)}
}

func (_c *MockTrackingStore_RestoreRun_Call) Run(run func(ctx context.Context, runID string)) *MockTrackingStore_RestoreRun_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTrackingStore_RestoreRun_Call) Return(_a0 *contract.Error) *MockTrackingStore_RestoreRun_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTrackingStore_RestoreRun_Call) RunAndReturn(run func(context.Context, string) *contract.Error) *MockTrackingStore_RestoreRun_Call {
	_c.Call.Return(run)
	return _c
}

// SearchExperiments provides a mock function with given fields: ctx, experimentViewType, maxResults, filter, orderBy, pageToken
func (_m *MockTrackingStore) SearchExperiments(ctx context.Context, experimentViewType protos.ViewType, maxResults int64, filter string, orderBy []string, pageToken string) ([]*entities.Experiment, string, *contract.Error) {
	ret := _m.Called(ctx, experimentViewType, maxResults, filter, orderBy, pageToken)

	if len(ret) == 0 {
		panic("no return value specified for SearchExperiments")
	}

	var r0 []*entities.Experiment
	var r1 string
	var r2 *contract.Error
	if rf, ok := ret.Get(0).(func(context.Context, protos.ViewType, int64, string, []string, string) ([]*entities.Experiment, string, *contract.Error)); ok {
		return rf(ctx, experimentViewType, maxResults, filter, orderBy, pageToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, protos.ViewType, int64, string, []string, string) []*entities.Experiment); ok {
		r0 = rf(ctx, experimentViewType, maxResults, filter, orderBy, pageToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Experiment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, protos.ViewType, int64, string, []string, string) string); ok {
		r1 = rf(ctx, experimentViewType, maxResults, filter, orderBy, pageToken)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, protos.ViewType, int64, string, []string, string) *contract.Error); ok {
		r2 = rf(ctx, experimentViewType, maxResults, filter, orderBy, pageToken)
	} else {
		if ret.Get(2) != nil {
			r2 = ret.Get(2).(*contract.Error)
		}
	}

	return r0, r1, r2
}

// MockTrackingStore_SearchExperiments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchExperiments'
type MockTrackingStore_SearchExperiments_Call struct {
	*mock.Call
}

// SearchExperiments is a helper method to define mock.On call
//   - ctx context.Context
//   - experimentViewType protos.ViewType
//   - maxResults int64
//   - filter string
//   - orderBy []string
//   - pageToken string
func (_e *MockTrackingStore_Expecter) SearchExperiments(ctx interface{}, experimentViewType interface{}, maxResults interface{}, filter interface{}, orderBy interface{}, pageToken interface{}) *MockTrackingStore_SearchExperiments_Call {
	return &MockTrackingStore_SearchExperiments_Call{Call: _e.mock.On("SearchExperiments", ctx, experimentViewType, maxResults, filter, orderBy, pageToken)}
}

func (_c *MockTrackingStore_SearchExperiments_Call) Run(run func(ctx context.Context, experimentViewType protos.ViewType, maxResults int64, filter string, orderBy []string, pageToken string)) *MockTrackingStore_SearchExperiments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(protos.ViewType), args[2].(int64), args[3].(string), args[4].([]string), args[5].(string))
	})
	return _c
}

func (_c *MockTrackingStore_SearchExperiments_Call) Return(_a0 []*entities.Experiment, _a1 string, _a2 *contract.Error) *MockTrackingStore_SearchExperiments_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockTrackingStore_SearchExperiments_Call) RunAndReturn(run func(context.Context, protos.ViewType, int64, string, []string, string) ([]*entities.Experiment, string, *contract.Error)) *MockTrackingStore_SearchExperiments_Call {
	_c.Call.Return(run)
	return _c
}

// SearchRuns provides a mock function with given fields: ctx, experimentIDs, filter, runViewType, maxResults, orderBy, pageToken
func (_m *MockTrackingStore) SearchRuns(ctx context.Context, experimentIDs []string, filter string, runViewType protos.ViewType, maxResults int, orderBy []string, pageToken string) ([]*entities.Run, string, *contract.Error) {
	ret := _m.Called(ctx, experimentIDs, filter, runViewType, maxResults, orderBy, pageToken)

	if len(ret) == 0 {
		panic("no return value specified for SearchRuns")
	}

	var r0 []*entities.Run
	var r1 string
	var r2 *contract.Error
	if rf, ok := ret.Get(0).(func(context.Context, []string, string, protos.ViewType, int, []string, string) ([]*entities.Run, string, *contract.Error)); ok {
		return rf(ctx, experimentIDs, filter, runViewType, maxResults, orderBy, pageToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string, string, protos.ViewType, int, []string, string) []*entities.Run); ok {
		r0 = rf(ctx, experimentIDs, filter, runViewType, maxResults, orderBy, pageToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Run)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string, string, protos.ViewType, int, []string, string) string); ok {
		r1 = rf(ctx, experimentIDs, filter, runViewType, maxResults, orderBy, pageToken)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, []string, string, protos.ViewType, int, []string, string) *contract.Error); ok {
		r2 = rf(ctx, experimentIDs, filter, runViewType, maxResults, orderBy, pageToken)
	} else {
		if ret.Get(2) != nil {
			r2 = ret.Get(2).(*contract.Error)
		}
	}

	return r0, r1, r2
}

// MockTrackingStore_SearchRuns_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchRuns'
type MockTrackingStore_SearchRuns_Call struct {
	*mock.Call
}

// SearchRuns is a helper method to define mock.On call
//   - ctx context.Context
//   - experimentIDs []string
//   - filter string
//   - runViewType protos.ViewType
//   - maxResults int
//   - orderBy []string
//   - pageToken string
func (_e *MockTrackingStore_Expecter) SearchRuns(ctx interface{}, experimentIDs interface{}, filter interface{}, runViewType interface{}, maxResults interface{}, orderBy interface{}, pageToken interface{}) *MockTrackingStore_SearchRuns_Call {
	return &MockTrackingStore_SearchRuns_Call{Call: _e.mock.On("SearchRuns", ctx, experimentIDs, filter, runViewType, maxResults, orderBy, pageToken)}
}

func (_c *MockTrackingStore_SearchRuns_Call) Run(run func(ctx context.Context, experimentIDs []string, filter string, runViewType protos.ViewType, maxResults int, orderBy []string, pageToken string)) *MockTrackingStore_SearchRuns_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string), args[2].(string), args[3].(protos.ViewType), args[4].(int), args[5].([]string), args[6].(string))
	})
	return _c
}

func (_c *MockTrackingStore_SearchRuns_Call) Return(_a0 []*entities.Run, _a1 string, _a2 *contract.Error) *MockTrackingStore_SearchRuns_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockTrackingStore_SearchRuns_Call) RunAndReturn(run func(context.Context, []string, string, protos.ViewType, int, []string, string) ([]*entities.Run, string, *contract.Error)) *MockTrackingStore_SearchRuns_Call {
	_c.Call.Return(run)
	return _c
}

// SetExperimentTag provides a mock function with given fields: ctx, experimentID, key, value
func (_m *MockTrackingStore) SetExperimentTag(ctx context.Context, experimentID string, key string, value string) *contract.Error {
	ret := _m.Called(ctx, experimentID, key, value)

	if len(ret) == 0 {
		panic("no return value specified for SetExperimentTag")
	}

	var r0 *contract.Error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *contract.Error); ok {
		r0 = rf(ctx, experimentID, key, value)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*contract.Error)
		}
	}

	return r0
}

// MockTrackingStore_SetExperimentTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetExperimentTag'
type MockTrackingStore_SetExperimentTag_Call struct {
	*mock.Call
}

// SetExperimentTag is a helper method to define mock.On call
//   - ctx context.Context
//   - experimentID string
//   - key string
//   - value string
func (_e *MockTrackingStore_Expecter) SetExperimentTag(ctx interface{}, experimentID interface{}, key interface{}, value interface{}) *MockTrackingStore_SetExperimentTag_Call {
	return &MockTrackingStore_SetExperimentTag_Call{Call: _e.mock.On("SetExperimentTag", ctx, experimentID, key, value)}
}

func (_c *MockTrackingStore_SetExperimentTag_Call) Run(run func(ctx context.Context, experimentID string, key string, value string)) *MockTrackingStore_SetExperimentTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockTrackingStore_SetExperimentTag_Call) Return(_a0 *contract.Error) *MockTrackingStore_SetExperimentTag_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTrackingStore_SetExperimentTag_Call) RunAndReturn(run func(context.Context, string, string, string) *contract.Error) *MockTrackingStore_SetExperimentTag_Call {
	_c.Call.Return(run)
	return _c
}

// SetTag provides a mock function with given fields: ctx, runID, key, value
func (_m *MockTrackingStore) SetTag(ctx context.Context, runID string, key string, value string) *contract.Error {
	ret := _m.Called(ctx, runID, key, value)

	if len(ret) == 0 {
		panic("no return value specified for SetTag")
	}

	var r0 *contract.Error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *contract.Error); ok {
		r0 = rf(ctx, runID, key, value)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*contract.Error)
		}
	}

	return r0
}

// MockTrackingStore_SetTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetTag'
type MockTrackingStore_SetTag_Call struct {
	*mock.Call
}

// SetTag is a helper method to define mock.On call
//   - ctx context.Context
//   - runID string
//   - key string
//   - value string
func (_e *MockTrackingStore_Expecter) SetTag(ctx interface{}, runID interface{}, key interface{}, value interface{}) *MockTrackingStore_SetTag_Call {
	return &MockTrackingStore_SetTag_Call{Call: _e.mock.On("SetTag", ctx, runID, key, value)}
}

func (_c *MockTrackingStore_SetTag_Call) Run(run func(ctx context.Context, runID string, key string, value string)) *MockTrackingStore_SetTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockTrackingStore_SetTag_Call) Return(_a0 *contract.Error) *MockTrackingStore_SetTag_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTrackingStore_SetTag_Call) RunAndReturn(run func(context.Context, string, string, string) *contract.Error) *MockTrackingStore_SetTag_Call {
	_c.Call.Return(run)
	return _c
}

// SetTraceTag provides a mock function with given fields: ctx, requestID, key, value
func (_m *MockTrackingStore) SetTraceTag(ctx context.Context, requestID string, key string, value string) error {
	ret := _m.Called(ctx, requestID, key, value)

	if len(ret) == 0 {
		panic("no return value specified for SetTraceTag")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, requestID, key, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTrackingStore_SetTraceTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetTraceTag'
type MockTrackingStore_SetTraceTag_Call struct {
	*mock.Call
}

// SetTraceTag is a helper method to define mock.On call
//   - ctx context.Context
//   - requestID string
//   - key string
//   - value string
func (_e *MockTrackingStore_Expecter) SetTraceTag(ctx interface{}, requestID interface{}, key interface{}, value interface{}) *MockTrackingStore_SetTraceTag_Call {
	return &MockTrackingStore_SetTraceTag_Call{Call: _e.mock.On("SetTraceTag", ctx, requestID, key, value)}
}

func (_c *MockTrackingStore_SetTraceTag_Call) Run(run func(ctx context.Context, requestID string, key string, value string)) *MockTrackingStore_SetTraceTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockTrackingStore_SetTraceTag_Call) Return(_a0 error) *MockTrackingStore_SetTraceTag_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTrackingStore_SetTraceTag_Call) RunAndReturn(run func(context.Context, string, string, string) error) *MockTrackingStore_SetTraceTag_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRun provides a mock function with given fields: ctx, runID, runStatus, endTime, runName
func (_m *MockTrackingStore) UpdateRun(ctx context.Context, runID string, runStatus string, endTime *int64, runName string) *contract.Error {
	ret := _m.Called(ctx, runID, runStatus, endTime, runName)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRun")
	}

	var r0 *contract.Error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *int64, string) *contract.Error); ok {
		r0 = rf(ctx, runID, runStatus, endTime, runName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*contract.Error)
		}
	}

	return r0
}

// MockTrackingStore_UpdateRun_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRun'
type MockTrackingStore_UpdateRun_Call struct {
	*mock.Call
}

// UpdateRun is a helper method to define mock.On call
//   - ctx context.Context
//   - runID string
//   - runStatus string
//   - endTime *int64
//   - runName string
func (_e *MockTrackingStore_Expecter) UpdateRun(ctx interface{}, runID interface{}, runStatus interface{}, endTime interface{}, runName interface{}) *MockTrackingStore_UpdateRun_Call {
	return &MockTrackingStore_UpdateRun_Call{Call: _e.mock.On("UpdateRun", ctx, runID, runStatus, endTime, runName)}
}

func (_c *MockTrackingStore_UpdateRun_Call) Run(run func(ctx context.Context, runID string, runStatus string, endTime *int64, runName string)) *MockTrackingStore_UpdateRun_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(*int64), args[4].(string))
	})
	return _c
}

func (_c *MockTrackingStore_UpdateRun_Call) Return(_a0 *contract.Error) *MockTrackingStore_UpdateRun_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTrackingStore_UpdateRun_Call) RunAndReturn(run func(context.Context, string, string, *int64, string) *contract.Error) *MockTrackingStore_UpdateRun_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTrackingStore creates a new instance of MockTrackingStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTrackingStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTrackingStore {
	mock := &MockTrackingStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
