//nolint:err113
package main

import (
	"bufio"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"io/fs"
	"net/http"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/iancoleman/strcase"

	"github.com/mlflow/mlflow-go/mlflow_go/go/cmd/generate/discovery"
)

func mkMethodInfoInputPointerType(methodInfo discovery.MethodInfo) *ast.StarExpr {
	return mkStarExpr(mkSelectorExpr(methodInfo.PackageName, methodInfo.Input))
}

// Generate a method declaration on an service interface.
func mkServiceInterfaceMethod(methodInfo discovery.MethodInfo) *ast.Field {
	return &ast.Field{
		Names: []*ast.Ident{ast.NewIdent(strcase.ToCamel(methodInfo.Name))},
		Type: &ast.FuncType{
			Params: &ast.FieldList{
				List: []*ast.Field{
					mkNamedField("input", mkMethodInfoInputPointerType(methodInfo)),
				},
			},
			Results: &ast.FieldList{
				List: []*ast.Field{
					mkField(mkStarExpr(mkSelectorExpr(methodInfo.PackageName, methodInfo.Output))),
					mkField(mkStarExpr(mkSelectorExpr("contract", "Error"))),
				},
			},
		},
	}
}

// Generate a service interface declaration.
func mkServiceInterfaceNode(
	endpoints map[string]any, interfaceName string, serviceInfo discovery.ServiceInfo,
) *ast.GenDecl {
	// We add one method to validate any of the input structs
	methods := make([]*ast.Field, 0, len(serviceInfo.Methods))

	for _, method := range serviceInfo.Methods {
		if _, ok := endpoints[method.Name]; ok {
			methods = append(methods, mkServiceInterfaceMethod(method))
		}
	}

	// Create an interface declaration
	return &ast.GenDecl{
		Tok: token.TYPE, // Specifies a type declaration
		Specs: []ast.Spec{
			&ast.TypeSpec{
				Name: ast.NewIdent(interfaceName),
				Type: &ast.InterfaceType{
					Methods: &ast.FieldList{
						List: methods,
					},
				},
			},
		},
	}
}

func saveASTToFile(fset *token.FileSet, file *ast.File, addComment bool, outputPath string) error {
	// Create or truncate the output file
	outputFile, err := os.Create(outputPath)
	if err != nil {
		return fmt.Errorf("could not create output file: %w", err)
	}
	defer outputFile.Close()

	// Use a bufio.Writer for buffered writing (optional)
	writer := bufio.NewWriter(outputFile)
	defer writer.Flush()

	if addComment {
		_, err := writer.WriteString("// Code generated by mlflow/go/cmd/generate/main.go. DO NOT EDIT.\n\n")
		if err != nil {
			return fmt.Errorf("could not add comment to generated file: %w", err)
		}
	}

	// Write the generated code to the file
	err = format.Node(writer, fset, file)
	if err != nil {
		return fmt.Errorf("could not write generated AST to file: %w", err)
	}

	return nil
}

//nolint:funlen
func mkAppRoute(method discovery.MethodInfo, endpoint discovery.Endpoint) ast.Stmt {
	urlExpr := &ast.BasicLit{Kind: token.STRING, Value: fmt.Sprintf(`"%s"`, endpoint.GetFiberPath())}

	// input := &protos.SearchExperiments
	inputExpr := mkAssignStmt(
		[]ast.Expr{ast.NewIdent("input")},
		[]ast.Expr{
			mkAmpExpr(&ast.CompositeLit{
				Type: mkSelectorExpr(method.PackageName, method.Input),
			}),
		})

	// if err := parser.ParseQuery(ctx, input); err != nil { return err }
	// if err := parser.ParseBody(ctx, input); err != nil { return err }
	var extractModel ast.Expr
	if endpoint.Method == http.MethodGet {
		extractModel = mkCallExpr(mkSelectorExpr("parser", "ParseQuery"), ast.NewIdent("ctx"), ast.NewIdent("input"))
	} else {
		extractModel = mkCallExpr(mkSelectorExpr("parser", "ParseBody"), ast.NewIdent("ctx"), ast.NewIdent("input"))
	}

	inputErrorCheck := mkIfStmt(
		mkAssignStmt([]ast.Expr{ast.NewIdent("err")}, []ast.Expr{extractModel}),
		errNotEqualNil,
		mkBlockStmt(returnErr),
	)

	// output, err := service.Method(input)
	outputExpr := mkAssignStmt([]ast.Expr{
		ast.NewIdent("output"),
		ast.NewIdent("err"),
	}, []ast.Expr{
		mkCallExpr(mkSelectorExpr("service", strcase.ToCamel(method.Name)), ast.NewIdent("input")),
	})

	// if err != nil {
	//     return err
	// }
	errorCheck := mkIfStmt(
		nil,
		errNotEqualNil,
		mkBlockStmt(
			mkReturnStmt(ast.NewIdent("err")),
		),
	)

	// return ctx.JSON(output)
	returnExpr := mkReturnStmt(mkCallExpr(mkSelectorExpr("ctx", "JSON"), ast.NewIdent("output")))

	// func(ctx *fiber.Ctx) error { .. }
	funcExpr := &ast.FuncLit{
		Type: &ast.FuncType{
			Params: &ast.FieldList{
				List: []*ast.Field{
					mkNamedField("ctx", mkStarExpr(mkSelectorExpr("fiber", "Ctx"))),
				},
			},
			Results: &ast.FieldList{
				List: []*ast.Field{
					mkField(ast.NewIdent("error")),
				},
			},
		},
		Body: &ast.BlockStmt{
			List: []ast.Stmt{
				inputExpr,
				inputErrorCheck,
				outputExpr,
				errorCheck,
				returnExpr,
			},
		},
	}

	return &ast.ExprStmt{
		// app.Get("/mlflow/experiments/search", func(ctx *fiber.Ctx) error { .. })
		X: mkCallExpr(
			mkSelectorExpr("app", strcase.ToCamel(endpoint.Method)), urlExpr, funcExpr,
		),
	}
}

func mkRouteRegistrationFunction(
	endpoints map[string]any, interfaceName string, serviceInfo discovery.ServiceInfo,
) *ast.FuncDecl {
	routes := make([]ast.Stmt, 0, len(serviceInfo.Methods))

	for _, method := range serviceInfo.Methods {
		for _, endpoint := range method.Endpoints {
			if _, ok := endpoints[method.Name]; ok {
				routes = append(routes, mkAppRoute(method, endpoint))
			}
		}
	}

	return &ast.FuncDecl{
		Name: ast.NewIdent(fmt.Sprintf("Register%sRoutes", interfaceName)),
		Type: &ast.FuncType{
			Params: &ast.FieldList{
				List: []*ast.Field{
					mkNamedField("service", mkSelectorExpr("service", interfaceName)),
					mkNamedField("parser", mkStarExpr(mkSelectorExpr("parser", "HTTPRequestParser"))),
					mkNamedField("app", mkStarExpr(ast.NewIdent("fiber.App"))),
				},
			},
		},
		Body: &ast.BlockStmt{
			List: routes,
		},
	}
}

func mkGeneratedFile(pkg, outputPath string, decls []ast.Decl) error {
	// Set up the FileSet and the AST File
	fset := token.NewFileSet()

	file := &ast.File{
		Name:  ast.NewIdent(pkg),
		Decls: decls,
	}

	err := saveASTToFile(fset, file, true, outputPath)
	if err != nil {
		return fmt.Errorf("could not save AST to file: %w", err)
	}

	return nil
}

const expectedImportStatements = 2

// Generate the service interface.
func generateServices(
	pkgFolder string,
	serviceInfo discovery.ServiceInfo,
	generationInfo ServiceGenerationInfo,
	endpoints map[string]any,
) error {
	decls := make([]ast.Decl, 0, len(endpoints)+expectedImportStatements)

	if len(endpoints) > 0 {
		decls = append(decls,
			mkImportStatements(
				`"github.com/mlflow/mlflow-go/mlflow_go/go/protos"`,
				`"github.com/mlflow/mlflow-go/mlflow_go/go/contract"`,
			))
	}

	decls = append(decls, mkServiceInterfaceNode(
		endpoints,
		generationInfo.ServiceName,
		serviceInfo,
	))

	fileName := generationInfo.FileNameWithoutExtension + ".g.go"
	pkg := "service"
	outputPath := filepath.Join(pkgFolder, "contract", pkg, fileName)

	return mkGeneratedFile(pkg, outputPath, decls)
}

func generateRouteRegistrations(
	pkgFolder string,
	serviceInfo discovery.ServiceInfo,
	generationInfo ServiceGenerationInfo,
	endpoints map[string]any,
) error {
	importStatements := []string{
		`"github.com/gofiber/fiber/v2"`,
		`"github.com/mlflow/mlflow-go/mlflow_go/go/server/parser"`,
		`"github.com/mlflow/mlflow-go/mlflow_go/go/contract/service"`,
	}

	if len(endpoints) > 0 {
		importStatements = append(
			importStatements,
			`"github.com/mlflow/mlflow-go/mlflow_go/go/protos"`,
		)
	}

	decls := []ast.Decl{
		mkImportStatements(importStatements...),
		mkRouteRegistrationFunction(endpoints, generationInfo.ServiceName, serviceInfo),
	}

	fileName := generationInfo.FileNameWithoutExtension + ".g.go"
	pkg := "routes"
	outputPath := filepath.Join(pkgFolder, "server", pkg, fileName)

	return mkGeneratedFile(pkg, outputPath, decls)
}

func mkCEndpointBody(serviceName string, method discovery.MethodInfo) *ast.BlockStmt {
	mapName := strcase.ToLowerCamel(serviceName) + "s"

	return &ast.BlockStmt{
		List: []ast.Stmt{
			// service, err := trackingServices.Get(serviceID)
			mkAssignStmt(
				[]ast.Expr{
					ast.NewIdent("service"),
					ast.NewIdent("err"),
				},
				[]ast.Expr{
					mkCallExpr(mkSelectorExpr(mapName, "Get"), ast.NewIdent("serviceID")),
				},
			),
			// 	if err != nil {
			//		return makePointerFromError(err, responseSize)
			//  }
			mkIfStmt(
				nil,
				errNotEqualNil,
				mkBlockStmt(
					mkReturnStmt(
						mkCallExpr(
							ast.NewIdent("makePointerFromError"),
							ast.NewIdent("err"),
							ast.NewIdent("responseSize"),
						),
					),
				),
			),
			//	return invokeServiceMethod(
			// 		service.GetExperiment,
			//		new(protos.GetExperiment),
			// 		requestData,
			// 		requestSize,
			// 		responseSize,
			// 	)
			mkReturnStmt(
				mkCallExpr(
					ast.NewIdent("invokeServiceMethod"),
					mkSelectorExpr("service", strcase.ToCamel(method.Name)),
					mkCallExpr(ast.NewIdent("new"), mkSelectorExpr("protos", method.Input)),
					ast.NewIdent("requestData"),
					ast.NewIdent("requestSize"),
					ast.NewIdent("responseSize"),
				),
			),
		},
	}
}

func mkCEndpoint(serviceName string, method discovery.MethodInfo) *ast.FuncDecl {
	functionName := fmt.Sprintf("%s%s", serviceName, strcase.ToCamel(method.Name))

	return &ast.FuncDecl{
		Doc: &ast.CommentGroup{
			List: []*ast.Comment{
				{
					Text: "//export " + functionName,
				},
			},
		},
		Name: ast.NewIdent(functionName),
		Type: &ast.FuncType{
			Params: &ast.FieldList{
				List: []*ast.Field{
					mkNamedField("serviceID", ast.NewIdent("int64")),
					mkNamedField("requestData", mkSelectorExpr("unsafe", "Pointer")),
					mkNamedField("requestSize", mkSelectorExpr("C", "int")),
					mkNamedField("responseSize", mkStarExpr(mkSelectorExpr("C", "int"))),
				},
			},
			Results: &ast.FieldList{
				List: []*ast.Field{
					mkField(mkSelectorExpr("unsafe", "Pointer")),
				},
			},
		},
		Body: mkCEndpointBody(serviceName, method),
	}
}

func mkCEndpoints(
	endpoints map[string]any, serviceName string, serviceInfo discovery.ServiceInfo,
) []*ast.FuncDecl {
	funcs := make([]*ast.FuncDecl, 0, len(endpoints))

	for _, method := range serviceInfo.Methods {
		if _, ok := endpoints[method.Name]; ok {
			funcs = append(funcs, mkCEndpoint(serviceName, method))
		}
	}

	return funcs
}

func generateEndpoints(
	pkgFolder string,
	serviceInfo discovery.ServiceInfo,
	generationInfo ServiceGenerationInfo,
	endpoints map[string]any,
) error {
	decls := []ast.Decl{
		mkImportStatements(`"C"`),
	}

	if len(endpoints) > 0 {
		decls = append(
			decls,
			mkImportStatements(
				`"unsafe"`,
				`"github.com/mlflow/mlflow-go/mlflow_go/go/protos"`,
			),
		)

		endpoints := mkCEndpoints(endpoints, generationInfo.ServiceName, serviceInfo)
		for _, endpoint := range endpoints {
			decls = append(decls, endpoint)
		}
	}

	fileName := generationInfo.FileNameWithoutExtension + ".g.go"
	outputPath := filepath.Join(pkgFolder, "extension", fileName)

	return mkGeneratedFile("main", outputPath, decls)
}

func generateSourceCode(pkgFolder string) error {
	services, err := discovery.GetServiceInfos()
	if err != nil {
		return fmt.Errorf("could not get service info: %w", err)
	}

	for _, serviceInfo := range services {
		generationInfo, ok := ServiceInfoMap[serviceInfo.Name]
		if !ok {
			continue
		}

		endpoints := make(map[string]any, len(generationInfo.ImplementedEndpoints))

		for _, endpoint := range generationInfo.ImplementedEndpoints {
			endpoints[endpoint] = nil
		}

		err = generateServices(pkgFolder, serviceInfo, generationInfo, endpoints)
		if err != nil {
			return err
		}

		err = generateRouteRegistrations(pkgFolder, serviceInfo, generationInfo, endpoints)
		if err != nil {
			return err
		}

		err = generateEndpoints(pkgFolder, serviceInfo, generationInfo, endpoints)
		if err != nil {
			return err
		}
	}

	return nil
}

var jsonFieldTagRegexp = regexp.MustCompile(`json:"([^"]+)"`)

// Inspect the AST of the incoming file and add a query annotation to the struct tags which have a json tag.
//
//nolint:funlen,cyclop
func addQueryAnnotation(generatedGoFile string) error {
	// Parse the file into an AST
	fset := token.NewFileSet()

	node, err := parser.ParseFile(fset, generatedGoFile, nil, parser.ParseComments)
	if err != nil {
		return fmt.Errorf("add query annotation failed: %w", err)
	}

	// Create an AST inspector to modify specific struct tags
	ast.Inspect(node, func(n ast.Node) bool {
		// Look for struct type declarations
		typeSpec, isTypeSpec := n.(*ast.TypeSpec)
		if !isTypeSpec {
			return true
		}

		structType, isStructType := typeSpec.Type.(*ast.StructType)

		if !isStructType {
			return true
		}

		// Iterate over fields in the struct
		for _, field := range structType.Fields.List {
			if field.Tag == nil {
				continue
			}

			tagValue := field.Tag.Value

			hasQuery := strings.Contains(tagValue, "query:")
			hasValidate := strings.Contains(tagValue, "validate:")
			validationKey := fmt.Sprintf("%s_%s", typeSpec.Name, field.Names[0])
			validationRule, needsValidation := validations[validationKey]

			if hasQuery && (!needsValidation || needsValidation && hasValidate) {
				continue
			}

			// With opening ` tick
			newTag := tagValue[0 : len(tagValue)-1]

			matches := jsonFieldTagRegexp.FindStringSubmatch(tagValue)
			if len(matches) > 0 && !hasQuery {
				// Modify the tag here
				// The json annotation could be something like `json:"key,omitempty"`
				// We only want the key part, the `omitempty` is not relevant for the query annotation
				key := matches[1]
				if strings.Contains(key, ",") {
					key = strings.Split(key, ",")[0]
				}
				// Add query annotation
				newTag += fmt.Sprintf(" query:\"%s\"", key)
			}

			if needsValidation {
				// Add validation annotation
				newTag += fmt.Sprintf(" validate:\"%s\"", validationRule)
			}

			// Closing ` tick
			newTag += "`"
			field.Tag.Value = newTag
		}

		return false
	})

	return saveASTToFile(fset, node, false, generatedGoFile)
}

func addQueryAnnotations(pkgFolder string) error {
	protoFolder := filepath.Join(pkgFolder, "protos")

	if _, pathError := os.Stat(protoFolder); os.IsNotExist(pathError) {
		return fmt.Errorf("the %s folder does not exist. Are the Go protobuf files generated?", protoFolder)
	}

	err := filepath.WalkDir(protoFolder, func(path string, _ fs.DirEntry, err error) error {
		if err != nil {
			return err
		}

		if filepath.Ext(path) == ".go" {
			err = addQueryAnnotation(path)
		}

		return err
	})
	if err != nil {
		return fmt.Errorf("could not add query annotation: %w", err)
	}

	return nil
}

const ExpectedNumberOfArguments = 2

//nolint:forbidigo
func main() {
	if len(os.Args) != ExpectedNumberOfArguments {
		fmt.Println("Usage: program <path to mlflow/go/pkg folder>")
		os.Exit(1)
	}

	pkgFolder := os.Args[1]
	if _, err := os.Stat(pkgFolder); os.IsNotExist(err) {
		fmt.Printf("The provided path does not exist: %s\n", pkgFolder)
		os.Exit(1)
	}

	if err := addQueryAnnotations(pkgFolder); err != nil {
		fmt.Printf("Error adding query annotations: %s\n", err)
		os.Exit(1)
	}

	if err := generateSourceCode(pkgFolder); err != nil {
		fmt.Printf("Error generating source code: %s\n", err)
		os.Exit(1)
	}

	fmt.Println("Successfully added query annotations and generated services!")
}
