// Code generated by mlflow/go/cmd/generate/main.go. DO NOT EDIT.

package service

import (
	"context"
	"github.com/mlflow/mlflow-go/pkg/protos"
	"github.com/mlflow/mlflow-go/pkg/contract"
)

type ModelRegistryService interface {
	contract.Destroyer
	GetLatestVersions(ctx context.Context, input *protos.GetLatestVersions) (*protos.GetLatestVersions_Response, *contract.Error)
}
