// Code generated by mlflow/go/cmd/generate/main.go. DO NOT EDIT.

package service

import (
	"github.com/gofiber/fiber/v2"
	"github.com/mlflow/mlflow-go/pkg/protos"
	"github.com/mlflow/mlflow-go/pkg/contract"
)

type ModelRegistryService interface {
	GetLatestVersions(ctx *fiber.Ctx, input *protos.GetLatestVersions) (*protos.GetLatestVersions_Response, *contract.Error)
}
