// Code generated by mlflow/go/cmd/generate/main.go. DO NOT EDIT.

package routes

import (
	"github.com/gofiber/fiber/v2"
	"github.com/mlflow/mlflow-go/pkg/server/parser"
	"github.com/mlflow/mlflow-go/pkg/contract/service"
)

func RegisterArtifactsServiceRoutes(service service.ArtifactsService, parser *parser.HTTPRequestParser, app *fiber.App) {
}
