name: Build

on:
  workflow_call:

permissions:
  contents: read

jobs:
  wheel:
    name: Build Python wheel
    strategy:
      matrix:
        # runner: [macos-latest, ubuntu-latest, windows-latest]
        python: ["3.12"] # ["3.8", "3.9", "3.10", "3.11", "3.12"]
        target: ["x86_64-linux-gnu"] # ["x86_64-linux-gnu", "aarch64-linux-gnu", "x86_64-macos", "aarch64-macos", "x86_64-windows-gnu"]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
          check-latest: true
          cache: false

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install mage
        run: go install github.com/magefile/mage@v1.15.0

      - name: Install our package in editable mode
        run: pip install -e .

      - name: Initialize MLflow repo
        run: mage repo:init

      - name: Run build target
        run: mage build ${{ matrix.target }}

