name: Build

on:
  workflow_call:

permissions:
  contents: read

jobs:
  wheel:
    name: Build Python wheel
    strategy:
      matrix:
        # runner: [macos-latest, ubuntu-latest, windows-latest]
        python: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      # Skip installation if tools are already present
      - name: Verify Xcode Command Line Tools
        run: |
          if ! xcode-select -p; then
            sudo xcode-select --install
          fi
      # Set the SDK path manually for CGO
      - name: Set SDK and CGO environment variables
        run: |
          SDK_PATH=$(xcrun --show-sdk-path)
          echo "CGO_CFLAGS=-isysroot $SDK_PATH" >> $GITHUB_ENV
          echo "CGO_LDFLAGS=-isysroot $SDK_PATH" >> $GITHUB_ENV
      # Install openresolv
      - name: Install dependencies (if needed)
        run: brew install openresolv || echo "openresolv already installed"  # Optional

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
          check-latest: true
          cache: false

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install mage
        run: go install github.com/magefile/mage@v1.15.0

      - name: Install our package in editable mode
        run: pip install -e .

      - name: Initialize MLflow repo
        run: mage repo:init

      - name: Run build target
        run: mage build

