name: CI

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
  schedule:
    # Run daily at 01:34 so we get notified if CI is broken before a pull request
    # is submitted.
    - cron: "34 1 * * *"

jobs:
  # lint:
  #   uses: ./.github/workflows/lint.yml

  # test:
  #   uses: ./.github/workflows/test.yml

  build:
    uses: ./.github/workflows/build.yml

  release:
    name: Release
    needs: 
      # - lint
      # - test
      - build
    # if: ${{ !github.event.repository.fork && github.event_name == 'push' && (startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/main') }}
    if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') }}
    permissions:
      actions: write
      contents: write
      pages: write
      id-token: write
    uses: ./.github/workflows/release.yml